In [15]:
import numpy as np
from problem_definition import ProblemDefinition
from aco import aco
from pso import pso
from sa import sa
from helpers import get_random_params, convert_to_solution

In [16]:
I = 20
N = 15
M = 12
K = 5
L = 5

p = get_random_params(I, N, M, K, L)
inst = ProblemDefinition(p)

In [17]:
def cost_no_ACO(x):
    return inst.cost_function(*convert_to_solution(x, inst))


def cost_with_ACO(x):
    return inst.cost_function(*convert_to_solution(x, inst, use_ACO=True))

In [18]:
lb = [0]*(4*I+N+M)
ub = [0.999999]*(4*I+N+M)

solution, cost = sa(cost_no_ACO, lb, ub, maxiter=100, display_progress=True)
solution, cost

100%|██████████| 100/100 [00:00<00:00, 888.85it/s]


(array([4.10891483e-01, 7.21592040e-01, 1.33865479e-01, 6.60936096e-01,
        6.39621051e-01, 6.30528030e-01, 6.90167571e-01, 4.46002225e-01,
        5.04001924e-01, 5.94085999e-01, 3.98464267e-01, 2.97972480e-01,
        2.20401206e-01, 6.14358724e-01, 1.39479469e-01, 5.49315670e-01,
        2.47832551e-01, 6.89475366e-01, 4.01270702e-01, 9.99666630e-02,
        3.43943422e-02, 8.67092113e-01, 2.77232922e-02, 7.02217218e-01,
        3.46348856e-01, 9.89433258e-01, 4.16212584e-01, 7.49376694e-01,
        6.69984662e-01, 9.07279257e-01, 7.35253798e-01, 6.66442051e-01,
        9.61787421e-01, 1.48042936e-01, 8.65463798e-01, 3.91952439e-01,
        3.74455467e-01, 8.65289977e-01, 8.44851965e-01, 9.05470763e-01,
        8.31629530e-01, 8.44736343e-01, 7.43093974e-01, 6.96448765e-01,
        2.77932701e-01, 4.74531863e-01, 5.32934139e-01, 6.89873521e-01,
        8.80561707e-01, 9.57629774e-01, 8.00060880e-04, 8.87979586e-01,
        3.62397127e-01, 8.99056179e-01, 9.90073611e-01, 5.497071

In [19]:
solution, cost = pso(cost_no_ACO, lb, ub, maxiter=10, swarmsize=16, processes=16, display_progress=True)
solution, cost

100%|██████████| 10/10 [00:00<00:00, 64.43it/s]


(array([3.88505511e-01, 7.29308116e-01, 2.22996681e-01, 0.00000000e+00,
        0.00000000e+00, 9.13344319e-02, 3.42854891e-01, 1.61125893e-01,
        1.12323819e-01, 6.03651445e-01, 6.16439663e-01, 2.34193151e-01,
        2.89398865e-01, 4.41847751e-02, 7.03088876e-01, 4.28776446e-01,
        8.69326201e-01, 8.04171558e-01, 4.69281235e-01, 4.19110244e-01,
        9.26988110e-01, 9.99999000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.10471751e-01, 3.55045128e-01, 5.89167219e-01,
        6.40418040e-01, 0.00000000e+00, 3.28268868e-03, 2.57010285e-01,
        5.68393134e-01, 9.99999000e-01, 9.97600033e-01, 5.40337127e-01,
        7.93813734e-02, 0.00000000e+00, 1.68156964e-01, 6.30524603e-01,
        6.79335779e-01, 8.07733053e-01, 9.76687079e-01, 1.89018598e-01,
        2.87848992e-04, 3.05154466e-01, 9.99999000e-01, 2.11082195e-01,
        1.22497247e-02, 5.38706943e-02, 1.81008988e-01, 2.93201956e-01,
        2.71606256e-01, 7.72019801e-01, 9.29344343e-01, 3.198637

In [20]:
lb = [0]*(2*I+N+M)
ub = [0.999999]*(2*I+N+M)

solution, cost = sa(cost_with_ACO, lb, ub, maxiter=100, display_progress=True)
solution, cost

100%|██████████| 100/100 [00:00<00:00, 416.92it/s]


(array([0.5357457 , 0.69656671, 0.5937178 , 0.77195142, 0.42730171,
        0.81588323, 0.47442811, 0.91379559, 0.70420501, 0.56288197,
        0.49053759, 0.42810388, 0.84184599, 0.25823207, 0.13568376,
        0.21390476, 0.10992553, 0.92609322, 0.84115956, 0.39676445,
        0.38638317, 0.3549346 , 0.06363218, 0.0492872 , 0.36880451,
        0.45860948, 0.61744486, 0.19457781, 0.92500521, 0.94269287,
        0.10313433, 0.73340879, 0.83731261, 0.71495087, 0.20133101,
        0.999999  , 0.89358789, 0.76439831, 0.47351011, 0.16926177,
        0.41052437, 0.49513227, 0.80840968, 0.82169784, 0.05700917,
        0.85380223, 0.53433443, 0.77796081, 0.3016191 , 0.05273108,
        0.70874163, 0.51255252, 0.8071802 , 0.94752544, 0.85103335,
        0.66024224, 0.56553271, 0.55563527, 0.39711655, 0.20199657,
        0.26310554, 0.58331022, 0.72881757, 0.20865978, 0.50516536,
        0.22254388, 0.38114517]),
 180.0)

In [21]:
solution, cost = pso(cost_with_ACO, lb, ub, maxiter=10, swarmsize=16, processes=16, display_progress=True)
solution, cost

100%|██████████| 10/10 [00:11<00:00,  1.14s/it]


(array([0.        , 0.999999  , 0.66980786, 0.57400942, 0.11940718,
        0.43086045, 0.44439658, 0.85051868, 0.14841217, 0.37201819,
        0.46540544, 0.72420725, 0.48978994, 0.68020135, 0.61075579,
        0.6483347 , 0.87068548, 0.48087878, 0.95347713, 0.70811399,
        0.94579962, 0.72121946, 0.        , 0.11640483, 0.26584017,
        0.54984894, 0.56326849, 0.57994511, 0.49223594, 0.29733203,
        0.5853359 , 0.62274037, 0.21901421, 0.78569325, 0.23943034,
        0.55490447, 0.86664003, 0.48248672, 0.17769244, 0.52139322,
        0.4399925 , 0.76328133, 0.21374166, 0.0328571 , 0.96210698,
        0.88782948, 0.30211476, 0.81734953, 0.43642247, 0.69350299,
        0.75471636, 0.79463913, 0.65256155, 0.46878905, 0.63854943,
        0.43700662, 0.49313674, 0.48625171, 0.999999  , 0.52538472,
        0.45020714, 0.6177833 , 0.48387835, 0.25189328, 0.98505843,
        0.39552779, 0.72306533]),
 97.0)